### ISSUE TITLE
WARN en.yml

### ISSUE THREAD

**Issue by wundertraume** [AdvancedPlugins/Jobs#10]
### Describe the bug

Every time you reboot jobs 
![image](https://github.com/AdvancedPlugins/Jobs/assets/118831819/03e9753f-4609-4a76-956d-47ecd61f70a1)

### How to reproduce

`/advancedjobs:advancedjobsadmin reload`

**Comment by KPGTB** [comment]
Hey! Problem has been fixed. Fix will be available in the next update
