### ISSUE TITLE
I can only see "main admin command" when I use command with {/ajadmin give points %player% %amount%}

### ISSUE THREAD

**Issue by BIACKC4T** [AdvancedPlugins/Jobs#12]
### Describe the bug

Nothing happens excepting printing "Main admin Command" when I use all of the commands.
Commands not working list. 
"./set points" , 
"./give points", 
"./reset points"

### How to reproduce

There's nothing I can do to fix it. There's no document. I read all config file, but there's no way to fix this.

### Screenshots / Videos

![image](https://github.com/AdvancedPlugins/Jobs/assets/126849815/da122355-c4c2-4aba-9f9d-f153b53f2b4a)

### Server Log

[05:17:15 INFO]: _BIackCat_ issued server command: /ajadmin give [05:17:19 INFO]: _BIackCat_ issued server command: /ajadmin levelup [05:17:29 INFO]: _BIackCat_ issued server command: /ajadmin set points _BIackCat_ 0

**Comment by KPGTB** [comment]
Hey! The problem has been fixed. Fix will be available in the next update

**Comment by BIACKC4T** [comment]
Thanks a lot!
