### ISSUE TITLE
HELP LINK FOR GRADIENT COLORS IN THE .YML OR WIKI

### ISSUE THREAD

**Issue by GJ-Euphory** [AdvancedPlugins/Jobs#13]
### Describe the feature

Recently I had a question about whether I could create hexadecimal colors but there was nowhere where it said how to create them (I had to ask on Discord to find out, disastrous for those who don't use Discord, although it gives them points in favor of having staff available), it would be good to be able to add the format used for hexadecimal colors in the .yml files (at the beginning of each file it can be) and from there attach a link to a page that allows you to create gradient colors with the format provided "{#dddddd }" which is AlonsoLiaga's.

https://alonsoaliaga.github.io/generator/

There, if you use the format: "Brackets {#rrggbb}" you could create hexadecimal colors in gradient.

![image](https://github.com/AdvancedPlugins/Jobs/assets/122542736/158f0d80-31e6-4e41-b053-219b303fa26d)

# For example:

![image](https://github.com/AdvancedPlugins/Jobs/assets/122542736/5bb51ef6-955a-41f3-b489-31d53b14d295)
![image](https://github.com/AdvancedPlugins/Jobs/assets/122542736/4e38a055-6133-4ea7-8194-08df625e3ad0)

**Comment by KPGTB** [comment]
Hey! I added official gradient support. It will be available in the next update. We will also update wiki

Gradient syntax
```
<gradient:FIRST_COLOR,SECOND_COLOR>TEXT</gradient>
```

Example

```
<gradient:#FF0000,#0000FF>Okay?</gradient>
```

It supports only 2 colors

**Comment by GJ-Euphory** [comment]
nice
