### ISSUE TITLE
The "brewer" job is abuseable.

### ISSUE THREAD

**Issue by GJ-Euphory** [AdvancedPlugins/Jobs#15]
### Describe the bug

Players can advance the potion brewing job by simply placing a glass vial with water (or other effects), making it count as brewing, and players can take advantage of:

- Place
- Withdraw
- Take
- Fill out

And so on without having elaborated anything.

### How to reproduce

They only need to place a potion in the potion holder and it already counts as a potion brewing.

![image](https://github.com/AdvancedPlugins/Jobs/assets/122542736/c17efe0e-7724-4af4-b307-f088dd78cfe6)

### Screenshots / Videos

![image](https://github.com/AdvancedPlugins/Jobs/assets/122542736/af40984e-df6b-43de-bc12-bc34fa138378)
![image](https://github.com/AdvancedPlugins/Jobs/assets/122542736/14fc2f69-82b1-447c-81a9-bee00102f662)
![image](https://github.com/AdvancedPlugins/Jobs/assets/122542736/8085a890-fa30-46ea-b159-f3cdbf994a98)

**Comment by KPGTB** [comment]
Hey! I made some changes in brew action which should fix your problem. It will be available in the next update. Also please make sure that you have enabled option `brewing-protection: true` in config.yml
