### ISSUE TITLE
Conditional and itemsadder support.

### ISSUE THREAD

**Issue by dinobossytnew** [AdvancedPlugins/Jobs#16]
### Describe the feature

Basically, support is requested from ItemsAdder to use it as material as it would be used, it would be ItemsAdder:namespace:iditemia. This is done to replace it with the AI material, and the model or image would be displayed. Also, I have one major concern; we need something very urgent, which is adding conditionals so that the job is activated. For example, if the job is a fighter, it should require not having a sword or any item that is air or barehanded.

**Comment by KPGTB** [comment]
Hey! This feature will be available in one of the next larger updates 😉
