### ISSUE TITLE
No rewards

### ISSUE THREAD

**Issue by Renssus** [AdvancedPlugins/Jobs#17]
### Describe the bug

If you level up one of your jobs you do not get any rewards or you get all rewards. There is no way to only do reward 1 for level 1, reward 2 for level 2.

### How to reproduce

If you but anything like 1, 2 ,3,4 or between [] or 1 * %level% at the level rewards or default rewards you still get nothing.

**Comment by GC-spigot** [comment]
Hi! We've set up a guide now, this should work on current 1.1.1 latest version without an update:
https://jobs.advancedplugins.net/tutorials/per-level-rewards

**Comment by Renssus** [comment]
It still doesnt work?
what did I do wrong.
I have read the new wiki page "per level-rewards" and copied it.

Glider.yml:
 
type: glide

variable:
  root: none

name: 'Glider'

# Required Progress
required-progress: "10 * %level%"

# Points given after task is completed
points-rewarded: "1 * %level%"

# Required points to access this job
required-points: 0

# Is this a premium job?
premium: false

# rewards are taken from rewards.yml file
default-rewards: "1 * %level%"

# when level-rewards contains level, give default & level rewards or only level-rewards
both-rewards: true

# levels info
level-rewards:
  1: 
    - level-1
  2: 
    - level-2
  3: 
    - level-3
  4: 
    - level-4
  5: 
    - level-5
  6: 
    - level-6
  7: 
    - level-7

notify-at-percentages: [ 10, 25, 50, 75, 100 ]

whitelisted-worlds: []
blacklisted-worlds: []
blacklisted-regions: []
whitelisted-regions: []

item:
  material: ELYTRA
  name: '&2✦ &a&lGlider&a Job &7[Lvl. %level%] '
  lore:
    - '&7 To level up in this job, you must'
    - '&7 glide for &a%required_progress% &7blocks.'
    - ''
    - '&2• &f&lCurrent Level &8» &7Lvl. %level% '
    - '&2• &f&lActive &8» %active%'
    - ''
    - '&a&lJob Progress'
    - '&2• &a%progress_bar% &7(&f%total_progress%&7/&f%required_progress%&7)'
    - ''
    - '&2• %action%'

And this is rewards.yml:
'level-1':
  type: command
  name: 'diamond'
  commands:
    - 'give %player% diamond 1'
'level-2':
  type: command
  name: 'diamond'
  commands:
    - 'give %player% diamond 2'
'level-3':
  type: command
  name: 'diamond'
  commands:
    - 'give %player% diamond 3'
'level-4':
  type: command
  name: 'diamond'
  commands:
    - 'give %player% diamond 4'
'level-5':
  type: command
  name: 'diamond'
  commands:
    - 'give %player% diamond 5'
'level-6':
  type: command
  name: 'diamond'
  commands:
    - 'give %player% diamond 6'
'level-7':
  type: command
  name: 'diamond'
  commands:
    - 'give %player% diamond 7'

So whats wrong with this code?

**Comment by GC-spigot** [comment]
I cant really test that, its not formatted. Use pastebin or code tags.

Ive tested rewards fully they work without any problems, default, per-level etc. so please provide formatted and we'll test

**Comment by Renssus** [comment]
My bad it works now! thank you for fixing the issue!
