### ISSUE TITLE
Include specific permissions for each job!

### ISSUE THREAD

**Issue by XMXcloud** [AdvancedPlugins/Jobs#19]
### Describe the feature

I noticed that the plugin lacks permissions for each job. I would like to suggest that in the next update, this feature be included for those who wish to use it for server modes such as Prison or Rankup, to assign permissions for each rankup.

I'm only interested in using the Premium System to sell VIP memberships, but I would appreciate this update.

**Comment by KPGTB** [comment]
Hey! I added optional setting 'permission' to job's config. It will be available in the next update
