### ISSUE TITLE
EXTREME BUG! BREAK SERVERS COMPLETELY!

### ISSUE THREAD

**Issue by GJ-Euphory** [AdvancedPlugins/Jobs#2]
### Describe the bug

Running the command "/advancedjobs:ajadmin reload" completely corrupts the server and causes the server to be compromised! It made my 156 plugins stop working and made my players destroy everything!

### How to reproduce

I was configuring the "lang" folder, the "en.yml" file trying to translate it into Spanish.

When finished try rewriting the file name from "en.yml" --> "es.yml", then change in the config.yml from "en" to "es".

By executing the command "/advancedjobs:ajadmin reload" the chaos began! all players could break things in safe zones and absolutely all plugins stopped working!

This was to complain and give the plugin 1 star, but I'm not like that and I really give them the opportunity to show that they are capable of solving the problem.

Now I have to try to solve the problem that people have been dying in the safe zones, losing things, what a mess...

![image](https://github.com/AdvancedPlugins/Jobs/assets/122542736/ca2bfb42-8f1a-42b3-b05f-065dc9444527)

![image](https://github.com/AdvancedPlugins/Jobs/assets/122542736/cea94041-e85d-461e-b9db-3064d953c2a1)

### Screenshots / Videos

![image](https://github.com/AdvancedPlugins/Jobs/assets/122542736/05eb792e-3d6d-4fa9-9bc6-fd3be45b2173)
![image](https://github.com/AdvancedPlugins/Jobs/assets/122542736/cca3507e-80c9-4254-be0d-745a12f934a8)
![image](https://github.com/AdvancedPlugins/Jobs/assets/122542736/837fe920-0e47-4197-84eb-f443937e2235)

After a reboot on the server...

![image](https://github.com/AdvancedPlugins/Jobs/assets/122542736/4df4baf6-345a-40ce-b54b-152d2a8728bb)

**Comment by KPGTB** [comment]
Hey! Thanks for reporting that issue. I will try to check what causes that problem and fix it as soon as possible

**Comment by KPGTB** [comment]
Problem should be fixed - Fix will be available in the next update
