### ISSUE TITLE
Can not change the maximum level of work

### ISSUE THREAD

**Issue by wundertraume** [AdvancedPlugins/Jobs#21]
### Describe the bug

Can not change the maximum level of work (including snake), set in the config 140, the result is still 100

### How to reproduce

`max-level: 150`

### Screenshots / Videos

![image](https://github.com/AdvancedPlugins/Jobs/assets/118831819/bba42a5a-0f01-400e-9398-10d05bd9c5ed)

**Comment by KPGTB** [comment]
Hey! It's not a bug. Plugin supports almost infinite job's level (Max INT `2147483647`). It's not possible for us (using our utils module) to make that large paginate menu with millions of pages. Currently, the progress menu shows "the closest hundred" as last level in "snake". When you reach 100lvl, it will extend to configured 150.
