### ISSUE TITLE
Add blacklist items!

### ISSUE THREAD

**Issue by wundertraume** [AdvancedPlugins/Jobs#22]
### Describe the feature

Add a blacklist for items and blocks, because doing everything via whitelist is total hell

**Comment by KPGTB** [comment]
Hey! I added basic blacklists support to AdvancedJobs and BattlePass. It will be available in the next update. To make a blacklist you will need to put `!` before every entry in variable root. Example:
```
variable: "!zombie OR !cow" # Any mob excluding zombie and cow
```
