### ISSUE TITLE
Add blocks to the blacklist

### ISSUE THREAD

**Issue by wundertraume** [AdvancedPlugins/Jobs#23]
### Describe the feature

Add blocks to the blacklist
![image](https://github.com/AdvancedPlugins/Jobs/assets/118831819/c1c11566-cdfe-479c-aa07-577e948aa7e3)

**Comment by KPGTB** [comment]
Hey! If block is in variable root (like i.e in mining job) you can use blacklist
Example:
```
variable: !dirt:0 OR !stone:0 # Any block excluding dirt and stone
```
