### ISSUE TITLE
Add option to specify how many progress gives you specific type of mob/block

### ISSUE THREAD

**Issue by KoalaServers** [AdvancedPlugins/Jobs#24]
### Describe the feature

Would be good to be able to configure what mobs need to be killed/rammed in the hunter job.

Kill:
    Chicken:
      income: 5.0
      points: 5
      experience: 5.0
    Cow:
      income: 6.0
      points: 5
      experience: 5.0

**Comment by KPGTB** [comment]
Hey! You can configure which mobs you need to kill to progress job:
Example:
```
variable: zombie OR cow
```
We also plan to introduce variables with special amount of points
