### ISSUE TITLE
Adding in Levels

### ISSUE THREAD

**Issue by TurretedAsh** [AdvancedPlugins/Jobs#27]
### Describe the feature

Hello team,

Would love to see a level feature added into the jobs instead of using the math calculate. As some jobs i want to make cant work with it

Example:

Level 1: 20
Level 2: 35
Level 3 : 70

As seen above i believe this would be very easy etc...

Cheers
Turretedash

**Comment by KPGTB** [comment]
Hey! This feature will be available in one of the next updates. Syntax:
```
special-required-progress:
    1: 5
    3: 10
    5: 20
```
