### ISSUE TITLE
Bug WorldGuard

### ISSUE THREAD

**Issue by LordYarkan** [AdvancedPlugins/Jobs#29]
### Describe the bug

Hello, I have an error with the AdvancedJobs plugin with the beekeeper job 
I am using the Proteccionstones plugin, which works together with WorldGuard. The hives that are protected can be bugged while progressing their work.

### How to reproduce

They don't finish the bottles and they don't collect honey either.
By giving many right clicks you pass the level quickly.
How can I deactivate the work for the meantime?

**Comment by KPGTB** [comment]
Hey! Fix will be available in the next update
