### ISSUE TITLE
Advanced Jobs edit UI not working.

### ISSUE THREAD

**Issue by TheMightyBlurr** [AdvancedPlugins/Jobs#32]
### Describe the bug

21.06 21:28:32 [Server] INFO This server is running Paper version 1.21-20-master@8b1d26d (2024-06-21T00:30:00Z) (Implementing API version 1.21-R0.1-SNAPSHOT)

Advanced Jobs editor opens but then doesn't let you edit anything, throws up errors in console, i have included the pastebin.

### How to reproduce

open jobs editor and try to edit jobs ion game

### Server Log

https://pastebin.com/5Y4ih9US

**Comment by KPGTB** [comment]
Hey! Fix will be available in the next update
