### ISSUE TITLE
      material: head:%player_name%

### ISSUE THREAD

**Issue by Tolmwn** [AdvancedPlugins/Jobs#34]
### Describe the bug

Its not showing the right head from the player

### How to reproduce

![image](https://github.com/AdvancedPlugins/Jobs/assets/136921445/6015af6d-81aa-4936-946c-389b619f2448)

### Server Log

https://mcpaste.io/1f27d004ec9fe2cc

**Comment by KPGTB** [comment]
Hey! Can you send me menu configuration file?

**Comment by Tolmwn** [comment]
It was a Bug from the last Version, now it's working all fine !
