### ISSUE TITLE
%time_left% bug

### ISSUE THREAD

**Issue by Tolmwn** [AdvancedPlugins/Jobs#35]
### Describe the bug

I tried to remove the %time_left% from the gui with the jobs and add it at the jobs menu but its not working. It's a bug ?

### How to reproduce

![image](https://github.com/AdvancedPlugins/Jobs/assets/136921445/5bfdc8f7-aa03-4fbc-86d7-5bb794aa723b)

**Comment by KPGTB** [comment]
Added %time_left% into portal menu. Will be available in the next update
