### ISSUE TITLE
/ajadmin reset jobs 

### ISSUE THREAD

**Issue by Tolmwn** [AdvancedPlugins/Jobs#39]
### Describe the bug

I just try to make my skript code to make a custom reset each month like a battle pass. I finish it but its not working because the plugin is not allow the console to use the command /ajadmin reset jobs and is need to confirm that action.

Can you please make the command that its allowed from console to be use and a change at confirm file that ppl can disable the confirm.

### How to reproduce

![image](https://github.com/AdvancedPlugins/Jobs/assets/136921445/63f26a0b-e8a2-477d-b9a3-ce6f87be86fd)
![image](https://github.com/AdvancedPlugins/Jobs/assets/136921445/eadba931-d8e4-41b8-bb72-b50c6bbcfc2e)

**Comment by KPGTB** [comment]
Duplicated #38
