### ISSUE TITLE
Add anti-abuse to craft action

### ISSUE THREAD

**Issue by tweeg939** [AdvancedPlugins/Jobs#41]
### Describe the feature

I apologize in advance for my English; I am using a translator. I wanted to express my thoughts regarding the "type craft" parameter in the Crafter job. There needs to be a protection method or a blacklist for certain items or something along those lines. Otherwise, a player can repeatedly convert a gold ingot into gold nuggets and back, which means their profession level increases and they earn money "out of thin air."

**Comment by KPGTB** [comment]
Will be added probably at the end of this month. Until update, you can add blacklist for crafter job. i.e. `variable: !iron_nugget:0  OR !gold_nugget:0`

**Comment by KPGTB** [comment]
Hey! I'm sorry, but creating an effective anti abuse system to `craft` action is much harder than I thought, so I changed the status of this feature to `Planned`. It will be available in the future, when we figure out how to make this system in the effective way.

Sorry for the inconvenience,
kpg_tb
