### ISSUE TITLE
Farmer Jobs Progress 

### ISSUE THREAD

**Issue by DemonFrost-KC** [AdvancedPlugins/Jobs#47]
### Describe the bug

Certain crops such as melon and potato aren't getting counted as a progress whenever someone join in farmer jobs.

https://github.com/user-attachments/assets/b9b4282f-70fb-4f42-9ba4-44eaaa2b5a0a

### How to reproduce

When someone join farmer job and try harvesting melon or potato, it doesn't work.

### Screenshots / Videos

https://github.com/user-attachments/assets/b9b4282f-70fb-4f42-9ba4-44eaaa2b5a0a

**Comment by DemonFrost-KC** [comment]
How is this resolved? No one gave me new plugin jar or anything to fix the bug in-game.

**Comment by KPGTB** [comment]
Hey! This bug will be fixed in one of the next larger updates 😉

**Comment by DemonFrost-KC** [comment]
Alright, thanks.
