### ISSUE TITLE
Add multiple types for 1 profession

### ISSUE THREAD

**Issue by PetitLu26** [AdvancedPlugins/Jobs#49]
### Describe the feature

Hello, I would like to be able to add several types in 1 job.

For example, in the jobs farmers we cannot add melons and watermelons. I think it's a shame.

Have a nice day.

**Comment by KPGTB** [comment]
Hey! Version 1.4.1 fixed pumpkins/melons/sugar cane problems in farmer job.  

(Don't forget that we have anti abuse systems, so pumpkins/melons/sugar canes placed by player won't progress action - it needs to be spawned naturally)

**Comment by KPGTB** [comment]
Hey! This feature will be available in one of the next updates.
