### ISSUE TITLE
wiki

### ISSUE THREAD

**Issue by wundertraume** [AdvancedPlugins/Jobs#5]
### Describe the bug

1) Give instructions on WIKI how to create `level-rewards:`
2) Give a link to AdvancedJobs from here: https://wiki.advancedplugins.net/
![image](https://github.com/AdvancedPlugins/Jobs/assets/118831819/50cb27bb-0342-4098-9682-149daf57dbbc)

### How to reproduce

-

**Comment by KPGTB** [comment]
Hey! To create special reward for specific level in job, use this template:
```
level-rewards:
    LEVEL: [REW_ID1, REW_ID2]
    LEVEL2: [REW_ID3, REW_ID4]
```
example:
```
level-rewards:
    10: [3,8]
    20: [4,10]
```
In this case, player will get reward number 3 and 8 on level 10, and reward 4 and 10 on level 20

@GC-spigot could you update wiki?
