### ISSUE TITLE
Jobs Advance \ Progress from "Breaking Blocks" that cannot be broken, E.G: Sugar Cane (World Guard).

### ISSUE THREAD

**Issue by PunchysGameRoom** [AdvancedPlugins/Jobs#50]
### Describe the bug

The bug is quite simple, if you have a job active, let's say Farmer since this is the Job I discovered it in.  If you "Break Protected Blocks" like how you break them and it says "Sorry, you cannot break that here." You still get Job progression from it, even though you actually never harvested the block.  I was able to get it with Sugar Cane, I have not tried anything else yet.

### How to reproduce

Activate a Job, go to a protected area and break some sugar cane, you will get progression on the Farmer Job even though you're not breaking any blocks.
![2024-08-08_14 07 42](https://github.com/user-attachments/assets/c8dee7df-681f-49a1-b094-4fd8e38e11ef)

### Screenshots / Videos

![2024-08-08_14 07 42](https://github.com/user-attachments/assets/7bde8482-033a-4936-a495-53fe420217db)

**Comment by KPGTB** [comment]
Hey! Fix will be available in the next update.

**Comment by PunchysGameRoom** [comment]
Thank you!
