### ISSUE TITLE
AdvancedJobs / Daily Reset Message

### ISSUE THREAD

**Issue by FrankkC24** [AdvancedPlugins/Jobs#52]
### Describe the bug

I attach this message that is not translatable in any of the plugin files, and according to what I consulted in the discord, I was told that all users see it. In cases of wanting to translate it to Spanish or similar it is not possible. 

### How to reproduce

It is sent when work restarts, I believe.

### Screenshots / Videos

![image](https://github.com/user-attachments/assets/11fd7fbb-e7d5-4f3c-bae5-9404faccf9af)

**Comment by KPGTB** [comment]
Hey! It will be added in one of the next updates
