### ISSUE TITLE
Explorer, Builder & Fisherman Jobs aren't working after updating the plugin.

### ISSUE THREAD

**Issue by DemonFrost-KC** [AdvancedPlugins/Jobs#55]
### Describe the bug

A few days ago, I reported that our Farmer Job wasn't working. You advised me to update the plugin to the latest version. After doing so, the Farmer Job is now functioning properly, but the Explorer, Builder and Fisherman jobs have stopped working.

### How to reproduce

Whenever a player try to apply on those job, and try to do the required job, the progress doesn't add up.

### Screenshots / Videos

https://cdn.discordapp.com/attachments/1273710287018791093/1273711960629710962/2024-08-16_02-28-42.mp4?ex=66bf9c33&is=66be4ab3&hm=1d46965f5365df15e68a3822a3ff08c86eae91ace3014c1b396a63468c8235c5&

### Server Log

https://mcpaste.io/e1dd7483f20bdfab

**Comment by PunchysGameRoom** [comment]
I have experienced this issue as well, and was getting ready to submit a ticket until I saw this thread.  So what happens, multiple jobs aren't working, I have mine set to 3.  If I activate the fisherman job, it works until I activate say, Runner. Then runner progresses only and not fisherman.

**Comment by DemonFrost-KC** [comment]
Yup, that's what my players are experiencing right now.

**Comment by GC-spigot** [comment]
I've forwarded this to our development team, it will be fixed asap. Sorry yall!

**Comment by KPGTB** [comment]
Hey! Fix will be available in the next update
