### ISSUE TITLE
Hunter Jobs Progress Bug

### ISSUE THREAD

**Issue by DemonFrost-KC** [AdvancedPlugins/Jobs#58]
### Describe the bug

Some players get stucked in certain levels at hunter jobs even if they already achieved the progress required and im not sure why

### How to reproduce

Join hunter jobs, level up, and at some point you'll get stucked.

### Screenshots / Videos

https://prnt.sc/kXGSA5dzFRoS
https://prnt.sc/W8stulIaqLnG

### Server Log

https://mcpaste.io/ae6be8417dba4f69

**Comment by KPGTB** [comment]
Hey! Did you change anything in this job?

**Comment by DemonFrost-KC** [comment]
Yup I did, I changed the required progress and income. What should I do to make it fixed?

**Comment by KPGTB** [comment]
Hey! Fix will be available in one of the next updates. After installing an updated version of plugin, progress will be fixed for these players
