### ISSUE TITLE
Very high usage in timings report

### ISSUE THREAD

**Issue by Vehzx** [AdvancedPlugins/Jobs#59]
### Describe the bug

As seen in these timings, BattlePass and AdvancedJobs use significantly more % than all my other plugins combined, but it's only the KillMobQuest that's causing it. I assume this is something to do with how the plugin tracks mob kills.

I have made a seperate bug report on github for BattlePass also.

https://timings.aikar.co/dev/?id=aab4da66acb4486189e521cfc466b3e3

Incase you need a reference to the discord ticket I opened, it's ticket #bp-sirjben-1831

### How to reproduce

I use default advanced jobs config, start a timings report with

/timings on

leave for 10min

/timings report

### Screenshots / Videos

![image](https://github.com/user-attachments/assets/dca5e8a9-37d9-4422-8295-e1f50a5e2ecc)

### Server Log

https://mcpaste.io/d4037d9ff311aaaa

**Comment by KPGTB** [comment]
Hey! Please use the latest version of AdvancedJobs (1.4.12). Problem should be solved
