### ISSUE TITLE
more variables for rewards.yml

### ISSUE THREAD

**Issue by Vehzx** [AdvancedPlugins/Jobs#61]
### Describe the feature

For example, lets say I want to exponentially increase a reward, but cap it to a certain limit, lets say 20.

"`(2 * %level%) * min(1 + 0.1 * (%level% ^ 1.5), 10)`"

`2 * %level%`  --> This ensures a base increase of 2 per level.

`min(1 + 0.1 * (%level% ^ 1.5), 10)`  --> This handles the exponential growth and caps it to 10 (so it won't increase by more than 20 per level when multiplied by 2)

In this example, min is a function that returns the smaller of two values. It can be used to make sure that the growth rate doesn't exceed a specific limit.

`1 + 0.1 * (%level% ^ 1.5)` allows exponential growth.
`min(..., 10)` ensures that the growth doesn’t exceed 10.

Of course we can do specific rewards as a solution, however adding a variable like this makes it much easier to do.

Again this is just one example variable, there are many more that could be thought of.

**Comment by KPGTB** [comment]
Hey! You can already use mathematical functions inside variables. Here is a list of all functions -> https://ezylang.github.io/EvalEx/references/functions.html
