### ISSUE TITLE
v1.4.17 generated an exception while executing task 178

### ISSUE THREAD

**Issue by Eclipsssse** [AdvancedPlugins/Jobs#63]
### Describe the bug

I keep getting this console error

### How to reproduce

I dont know how to reproduce it

### Screenshots / Videos

[https://imgur.com/KL9IxjL](url)
![Chat 178](https://github.com/user-attachments/assets/f259f26e-1e7a-48fb-a5b4-0eee84761a53)

### Server Log

https://mcpaste.io/79b20bda71dbf6a2

**Comment by KPGTB** [comment]
Hey! Fix will be available in the next update
