### ISSUE TITLE
Vault API support for progressive actions.

### ISSUE THREAD

**Issue by lucasdimatteo** [AdvancedPlugins/Jobs#64]
### Describe the feature

Hello,

Thank you for adding payments for progressive actions, it is very useful and users love earning an extra incentive until they complete the level.

There is a performance issue though, (in scale), I'm using Purpur 1.21.1 with top tier dedicated hardware.

![spark](https://github.com/user-attachments/assets/553b4187-ef03-4cd4-9b33-99ae98db8254)

Only with 10 active players, the AdvancedJobs plugin and CMI, together, can use up to 1% of the Server thread, when the rest of my plugins such as Quests, Lands, Insights, etc. do not consume even 0.05% of the server. 98% (of 44%) of the server thread that indicates CMI is due to the commands that AdvancedJobs executes.

If it works like this on a test server, I don't know what to expect on a production server with 240 players.

Please add support for Vault to avoid intensive use of these commands.

**Comment by KPGTB** [comment]
Hey! Will be available in the next update
