### ISSUE TITLE
The arrows to go forward don't work for me

### ISSUE THREAD

**Issue by ernesto-I** [AdvancedPlugins/Jobs#66]
### Describe the bug

When I enter the jobs menu and click the next arrow to show the other jobs, it doesn't work for me.

### How to reproduce

I enter the menu, go to the jobs section, click on the next arrow and it does nothing.

### Screenshots / Videos

https://youtu.be/AlzrSAgWqxw

**Comment by KPGTB** [comment]
Hey! Are you sure that you have more than 10 active jobs? By default, plugin choose 10 free and 10 premium jobs every day and set them available. You can modify it in config (`jobs-reset` section). After that, remember to refresh jobs list `/aja refresh jobs`.
