### ISSUE TITLE
Permissions don't work

### ISSUE THREAD

**Issue by tantaf123** [AdvancedPlugins/Jobs#67]
### Describe the bug

The bypass rules permission doesn't work, does nothing. Jben tested it, it's not working.

### How to reproduce

a

### Screenshots / Videos

a

### Server Log

a

**Comment by KPGTB** [comment]
Hey! Which permission do you mean?

**Comment by tantaf123** [comment]
The bypass ones.

**Comment by tantaf123** [comment]
![image_2024-10-23_165925090](https://github.com/user-attachments/assets/2e811971-5d30-4787-bb08-3c4a55449dff)
like these ones the bypass things.

**Comment by KPGTB** [comment]
You reported it in a wrong place 😅 This is AdvancedJobs repository. Please report it there -> https://github.com/AdvancedPlugins/Chat/issues
