### ISSUE TITLE
Leaderboard bug

### ISSUE THREAD

**Issue by ghost** [AdvancedPlugins/Jobs#70]
### Describe the bug

When you click on the leaderboard a very big error appears

### How to reproduce

Occurs when you click on the leaderboard

### Screenshots / Videos

![image](https://github.com/user-attachments/assets/38f9d61b-7fbb-4007-959c-51f465489683)

### Server Log

https://mclo.gs/QZBaY0B

**Comment by KPGTB** [comment]
Hey! Can you send me your configuration of leaderboard menu from AdvancedJobs/menus folder?

**Comment by KPGTB** [comment]
I made small fix to hide this error, but it's probably problem with your configuration

**Comment by AleeJoo** [comment]
this is my configuration
https://mclo.gs/9cLooAr

**Comment by ghost** [comment]
> I made small fix to hide this error, but it's probably problem with your configuration

this is my configuration
https://mclo.gs/9cLooAr

**Comment by KPGTB** [comment]
Hey! Please check if version 1.5.18 fixed your issue and leaderboard works correctly
