### ISSUE TITLE
Title Placeholders 

### ISSUE THREAD

**Issue by wundertraume** [AdvancedPlugins/Jobs#9]
### Describe the feature

Add the ability for Placeholders to work in the title, like `%job%` in `progress.yml`
![image](https://github.com/AdvancedPlugins/Jobs/assets/118831819/a2d4b968-2152-48f8-a53d-b36aa38de4c9)
![image](https://github.com/AdvancedPlugins/Jobs/assets/118831819/1e62ad45-626d-4920-b448-f8bc8b120355)

**Comment by KPGTB** [comment]
Hey! I added %job% placeholder into progress menu. It will be available in the next update
